[package]
name = "ac2_definition"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "*"
num-traits = "0.2.19"
num-derive = "*"
